<div class="head-cls custom">
	<a href="https://gojeepsters.com/build-your-jeep">
		<img src="https://gojeepsters.com/pub/media/wysiwyg/gojeep.jpg">
	</a>
</div>

<style>
	.page-header .header.content{    width: 40% !important;float: left;}
	.page-header .header.content > a{    float: left;    margin-left: 5em;}
	.page-header .header.content a.logo img{float: left;}
	.head-cls.custom img{width:50%;}
	.head-cls.custom{    width: auto;    margin-top: -6em;	    margin-right: -29em;}
	@media screen and (max-width: 1023px) and (min-width: 768px){
	.page-header .head-cls.custom{
		    position: relative !important;
	}
	.page-header .header.content > a{    margin-left: 0;}
	}
	.head-cls.custom{
		    margin-top: -6em;    margin-right: -12em;
	}
	.head-cls.custom img{    width: 80%;}
	@media screen and (max-width: 1200px) and (min-width: 1024px){
		  .head-cls.custom{
		  text-align: right;    width: 130%;margin-right: -29em;}
		.page-header .header.content > a{
			    margin-left: 1em;
		}
		.head-cls.custom img{    width: 50%;}
	}
	
</style>