<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Finder
 */
?>
<?php if ($block->getButtonsHtml()): ?>
    <div class="page-actions"><?= $block->getButtonsHtml() ?></div>
<?php endif; ?>
<?= $block->getGridHtml() ?>

<?php /** Fix for js event in input page input */ ?>
<script>
    require(['mage/adminhtml/grid'], function () {

        varienGrid.prototype.inputPage = function (event, maxNum) {
            var element = Event.element(event);
            var keyCode = event.keyCode || event.which;
            if (keyCode == Event.KEY_RETURN) {
                this.setPage(element.value);
            }
            if (keyCode > 47 && keyCode < 58) {

            }
            else {
                Event.stop(event);
            }
        };
    });
</script>

<script type="text/x-magento-init">
{
    "body": {
        "Amasty_Finder/js/amfinder": {}
    }
}
</script>