<div class="add_banners">
    <div class="add-bnr-lft">
        
        <div class="add-bnr-lft-cnt-img">
            <!--<img src="<?php echo $block->getBaseurl(); ?>pub/media/wysiwyg/home/holder_small1.png" />-->
            <div class="add-bnr-lft-cnt">
            <h2>Elegant and in style!</h2>
            <h3>Complete your look with exclusive brands</h3>
            </div>
        </div>
        
        <div class="add-bnr-lft-cnt-img1">
            <div class="add-bnr-lft-cnt1">
            <h2>Your fresh look!</h2>
            <h3>The hottest spring styles</h3>
            </div>
        </div>
        
    </div>
    <div class="add-bnr-rgt">
        <div class="add-bnr-rgt-cnt-img">
            <div class="add-bnr-rgt-cnt1">
            <h2>The Jeep Superstore!</h2>
            <h3>Speacialize in Package deals</h3>
            <a class="shp_now" href="<?php echo $block->getBaseurl(); ?>accessories/bumpers.html">SHOP NOW</a>
            
            </div>
        </div>
    </div>
    
</div>

<div class="add_banners" style="margin-top: 45px;">
    <div class="add-bnr-lft1">
        
        <div class="add-bnr-lft-cnt-img2">
            <!--<img src="<?php echo $block->getBaseurl(); ?>pub/media/wysiwyg/home/holder_small1.png" />-->
            <div class="add-bnr-lft-cnt3">
                <div class="ban_holder1">
                <h2>Brand new Wheels!</h2>
                <h3>Designed with your total</h3>
                <h4>Experience in mind </h4>
                <a href="<?php echo $block->getBaseurl(); ?>wheel-tire/wheels.html"><span>Shop now!</span></a>
                </div>
            </div>
        </div>
    </div>
    <div class="add-bnr-lft1 add-bnr-padd">
        <div class="add-bnr-lft-cnt-img3">
            <div class="add-bnr-lft-cnt3">
            <div class="ban_holder2">
            <h2>Want to look your best?</h2>
            <h3>Find must-have styles for this spring</h3>
            <h4>New spring colors and styles</h4>
            </div>
            </div>
        </div>
        
    </div>
    
    <div class="add-bnr-lft1">
        
        <div class="add-bnr-lft-cnt-img2">
            <!--<img src="<?php echo $block->getBaseurl(); ?>pub/media/wysiwyg/home/holder_small1.png" />-->
            <div class="add-bnr-lft-cnt3">
                <div class="ban_holder1">
                <h2>Brand new Wheels!</h2>
                <h3>Designed with your total</h3>
                <h4>Experience in mind </h4>
                <a href="<?php echo $block->getBaseurl(); ?>wheel-tire/wheels.html"><span>Shop now!</span></a>
                </div>
            </div>
        </div>
    </div>
    <div class="add-bnr-lft1 add-bnr-padd">
        <div class="add-bnr-lft-cnt-img3">
            <div class="add-bnr-lft-cnt3">
            <div class="ban_holder2">
            <h2>Want to look your best?</h2>
            <h3>Find must-have styles for this spring</h3>
            <h4>New spring colors and styles</h4>
            </div>
            </div>
        </div>
        
    </div>
    <div class="add-bnr-lft1">
        <div class="add-bnr-lft-cnt-img4">
            <div class="add-bnr-lft-cnt3">
            <div class="ban_holder3">
            <h2>Find Your Look <br>Compare new frames </h2>
            <h3>Match your face shape, style and personality!</h3>
            <a><span>Shop now!</span></a>
        </div>
            </div>
        </div>
        
    </div>
    
</div>
