<iframe 
    id="nestedIFrame"
    allowtransparency="true" 
    width="100%"
    scrolling="no" 
    frameborder=0 
    marginheight="0" 
    marginwidth="0" 
    src="//www.interactivegarage.com/jeepsters/">
</iframe>



<script type="text/javascript" src="//www.interactivegarage.com/scripts/iframeResizer.min.js"></script>

<script type="text/javascript">

	iFrameResize({log:false, checkOrigin:false});

</script>