<?php
//custom template
$objectmanager = \Magento\Framework\App\ObjectManager::getInstance();
$currentCategoryId = $objectmanager->create('Magento\Catalog\Model\Layer\Resolver')->get()->getCurrentCategory()->getId();
$currenCategoryUrl = $objectmanager->create('Magento\Catalog\Model\Layer\Resolver')->get()->getCurrentCategory()->getUrl();
$categoryData = $objectmanager->get('\Magento\Catalog\Model\CategoryFactory')->create()->load($currentCategoryId);
$allcategoryproduct = $categoryData->getProductCollection()->addAttributeToSelect('*')->addAttributeToFilter('status',1);


    $getContent = $categoryData->getData('has_category_finder'); //is_home_page = your attribute code
if($getContent === '0'){	
$_productCollection = $block->getNews();

	if ($block->getPagerHtml()): ?>
	<div class="toolbar toolbar-products">
                    <div class="modes">
            <strong class="modes-label" id="modes-label">View as</strong>
                        <strong title="Grid" class="modes-mode active mode-grid" data-value="grid">
                <span>Grid</span>
            </strong>
                                    <a class="modes-mode mode-list" title="List" href="#" data-role="mode-switcher" data-value="list" id="mode-list" aria-labelledby="modes-label mode-list">
                <span>List</span>
            </a>
                        </div>
        
        <p class="toolbar-amount" id="toolbar-amount">
            <span class="toolbar-number toolbar-num"><?php echo count($allcategoryproduct). 'items';?></span></p>

        
    
        
                <div class="pages">
            <strong class="label pages-label" id="paging-label">Page</strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
            
            
            
                                                <li class="item current">
                        <strong class="page">
                            <span class="label">You're currently reading page</span>
                            <span>
							<?php 
							if($this->getRequest()->getParam('p')){
								echo $this->getRequest()->getParam('p');
							}else{
								echo '1';
							}
							?>
							
							</span>
                        </strong>
                    </li>
                                                                <li class="item">
                        <a href="https://gojeepsters.99stockpics.com/jeep-parts/bumpers.html?find=jeep-gladiator-2020-jtu-4-door-17789&amp;p=2&amp;sid=JAcyZNJKru" class="page">
                            <span class="label">Page</span>
                            <span>2</span>
                        </a>
                    </li>
                                                                <li class="item">
                        <a href="https://gojeepsters.99stockpics.com/jeep-parts/bumpers.html?find=jeep-gladiator-2020-jtu-4-door-17789&amp;p=3&amp;sid=JAcyZNJKru" class="page">
                            <span class="label">Page</span>
                            <span>3</span>
                        </a>
                    </li>
                                                                <li class="item">
                        <a href="https://gojeepsters.99stockpics.com/jeep-parts/bumpers.html?find=jeep-gladiator-2020-jtu-4-door-17789&amp;p=4&amp;sid=JAcyZNJKru" class="page">
                            <span class="label">Page</span>
                            <span>4</span>
                        </a>
                    </li>
                                                                <li class="item">
                        <a href="https://gojeepsters.99stockpics.com/jeep-parts/bumpers.html?find=jeep-gladiator-2020-jtu-4-door-17789&amp;p=5&amp;sid=JAcyZNJKru" class="page">
                            <span class="label">Page</span>
                            <span>5</span>
                        </a>
                    </li>
                            
            
            
                            <li class="item pages-item-next">
                                        <a class="action  next" href="https://gojeepsters.99stockpics.com/jeep-parts/bumpers.html?find=jeep-gladiator-2020-jtu-4-door-17789&amp;p=2&amp;sid=JAcyZNJKru" title="Next">
                        <span class="label">Page</span>
                        <span>Next</span>
                    </a>
                </li>
                        </ul>
        </div>
        
    
    

        <div class="field limiter">
    <label class="label" for="limiter">
        <span>Show</span>
    </label>
    <div class="control">
        <select id="limiter" data-role="limiter" class="limiter-options">
                            <option value="9" selected="selected">
                    9                </option>
                            <option value="15">
                    15                </option>
                            <option value="30">
                    30                </option>
                    </select>
    </div>
    <span class="limiter-text">per page</span>
</div>

                    <div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter">Sort By</label>
    <select id="sorter" data-role="sorter" class="sorter-options">
                    <option value="position">
                Position            </option>
                    <option value="name">
                Product Name            </option>
                    <option value="price" selected="selected">
                Price            </option>
                    <option value="wheel_size">
                Wheel Size            </option>
            </select>
            <a title="Set Descending Direction" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span>Set Descending Direction</span>
        </a>
    </div>
	<?php
	if($this->getRequest()->getParam('find')){
		$findParam =$this->getRequest()->getParam('find');
	}else{
		$findParam = '';
	}
	if($this->getRequest()->getParam('product_list_order')){
		$product_list_order = $this->getRequest()->getParam('product_list_order');
	}else{
		$product_list_order = '';
	}
	if($this->getRequest()->getParam('product_list_dir')){
		$product_list_dirs = $this->getRequest()->getParam('product_list_dir');
	}else{
		$product_list_dirs = '';
	}
	?>
	<script>
		require(['jquery'],function($){
			var selVal = $('#sorter option:selected').val();
			$(document).on('change','#sorter',function(){
				//var currentPageUrl = window.location.href;
				//$(this).siblings('.sorter-action');
				var findParam = "<?php echo $findParam?>";
				var product_list_dirs = "<?php echo $product_list_dirs?>";
				if(findParam !== "" && product_list_dirs !==""){
					var findParamUrl = '?find='+findParam;
					if(product_list_dirs=='desc'){
							product_list_dirs='asc';
						}else{
							product_list_dirs='desc';
						}
					var currUrl = '<?php echo $currenCategoryUrl?>'+findParamUrl+'&product_list_order='+$(this).val()+'&product_list_dir='+product_list_dirs;
				}else{
					var currUrl = '<?php echo $currenCategoryUrl?>'+'?product_list_order='+$(this).val()+'&product_list_dir='+product_list_dirs;
				}
				
				window.location.href = currUrl;
			});
			
			$(document).on('click','.sorter-action',function(){
				//var currentPageUrl = window.location.href;
				//$(this).siblings('.sorter-action');
				var findParam = "<?php echo $findParam?>";
				if(findParam !== ""){
					var findParamUrl = '?find='+findParam;
					var product_list_dirs = "<?php echo $product_list_dirs?>";
					if(product_list_dirs !== ""){
						if(product_list_dirs=='desc'){
							product_list_dirs='asc';
						}else{
							product_list_dirs='desc';
						}
						var currUrl = '<?php echo $currenCategoryUrl?>'+findParamUrl+'&product_list_order='+$('#sorter').val()+'&product_list_dir='+product_list_dirs;
					}else{
						var currUrl = '<?php echo $currenCategoryUrl?>'+'?product_list_order='+$('#sorter').val()+'&product_list_dir=desc';
					}
				}else{
					var product_list_dirs = "<?php echo $product_list_dirs?>";
					if(product_list_dirs){
						if(product_list_dirs=='desc'){
						var currUrl = '<?php echo $currenCategoryUrl?>'+'?product_list_order='+$('#sorter').val()+'&product_list_dir=asc';
						}else{
						var currUrl = '<?php echo $currenCategoryUrl?>'+'?product_list_order='+$('#sorter').val()+'&product_list_dir=desc';	
						}
						
					}else{
						if(product_list_dirs=='desc'){
						var currUrl = '<?php echo $currenCategoryUrl?>'+'?product_list_order='+$('#sorter').val()+'&product_list_dir=asc';
						}else{
						var currUrl = '<?php echo $currenCategoryUrl?>'+'?product_list_order='+$('#sorter').val()+'&product_list_dir=asc';	
						}
					}
					
				}
				
				window.location.href = currUrl;
			});
			$('.mode-list').click(function(){
				var newurl = window.location.href+'&product_list_mode=list';
				window.history.pushState({path:newurl},'',newurl);
				$('.grid-mode').hide();
				$('.list-mode').show();
				$('.product-item-actions').each(function(){
					$(this).show();
				});
				$(this).find('.product-item-inner').css({'position':'relative','top':'12em','float':'left','width':'50%'});
				$(this).find('.product-item-actions').show();
				$('li.item.product.product-item').hover(function(){
				$(this).find('.product-item-inner').css({'position':'relative','top':'12em','float':'left','width':'50%'});
				$(this).find('.product-item-actions').show();
				});
				$('li.item.product.product-item').mouseout(function(){
					$('.product-item-actions').each(function(){
						$(this).show();
					});
				});
				
			});
			$('.mode-grid').click(function(){
				var newurl = window.location.href+'&product_list_mode=grid';
				window.history.pushState({path:newurl},'',newurl);
				$('.list-mode').hide();
				$('.grid-mode').show();
			});
			// window.history.pushState({path:newurl},'',newurl);
			var product_list_order_list = '<?php echo $product_list_order;?>';
				if(product_list_order_list !==''){
					//$('#sorter option:selected').val(product_list_order_list);
					$('#sorter').val(product_list_order_list);
				}
		});
	</script>
            </div>
    <?php 
		endif; 
		setcookie("find", "", time()-1); 
	
	$_helper = $this->helper('Magento\Catalog\Helper\Output');

$outofstockEnable = $this->getConfig('outofstock_product/outofstockproduct/enableoutofstock');
$outofstockLabelImage = $this->getConfig('outofstock_product/outofstockproduct/showstock_label_image');
$outofstockTitle = $this->getConfig('outofstock_product/outofstockproduct/titleoutofstock');
$outofstockImage = $this->getConfig('outofstock_product/outofstockproduct/imageoutofstock');
$imageUrl = $this->getMediaUrl() . 'outofstockimage/' . $outofstockImage;
$outofstockPositionLabel = $this->getConfig('outofstock_product/outofstockproduct/showstock_position_label');
$outofstockPositionImage = $this->getConfig('outofstock_product/outofstockproduct/showstock_position_image');
$outofstockImageHeight = $this->getConfig('outofstock_product/outofstockproduct/imageheightoutofstock');
$outofstockImagewidth = $this->getConfig('outofstock_product/outofstockproduct/imagewidthoutofstock');
	$cateinstance = $objectmanager->create('Magento\Catalog\Model\CategoryFactory');
	
$cateid = '413';
$viewMode ='list';
$helperImport  = $objectmanager->get('\Magento\Catalog\Helper\Image');
$width = 100;
$height = 100;
$i=0;
if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php  echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
		
	  <ol class="products list items product-items grid-mode">
        <?php foreach ($_productCollection as $product) : ?>

		<?php
		$imageUrl = $helperImport->init($product, 'product_page_image_small')
                ->setImageFile($product->getSmallImage()) // image,small_image,thumbnail
                ->resize(380)
                ->getUrl();
		
		?>
            <li class="item product product-item loop-<?php echo $i?>" style="height:550px;width:33.3%">
			<div class="product-item-info" >
				  <div class="product-img-block">
                         <a href="<?php echo $product->getProductUrl();?>" class="product photo product-item-photo" tabindex="-1">
						 <span class="product-image-container" style="width:300px;height:400px;">
							<span class="product-image-wrapper" style="padding-bottom: 125%;">
								<img class="product-image-photo" src="<?php echo $imageUrl;?>" max-width="300" max-height="375" alt=""></span>
						</span>
						<div class="pro-overlay"></div>
						</a>
						<div class="product-item-inner">
						
						<div class="product actions product-item-actions">
								
                                    
									<?php if ($product->getIsSalable()): ?>
                                            <!--<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>-->
											<div class="actions-primary">
				<button type="submit" id="product-item-<?php echo $product->getId() ?>" title="Add to Cart" class="product-item action tocart primary"><span>Add to Cart</span></button> 
									</div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
									<div class="actions-secondary">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>' class="action towishlist" data-action="add-to-wishlist">
											<span>Add to wishlist</span>
										</a>

                                    <?php endif; ?>
									<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                <a href="#"
                                   class="action tocompare"
                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product); ?>'
                                   role="button">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                </a>
                                    </div>
								
						</div>
						</div>
				
						
						
						
						
                    </div>
							
						<div class="product details product-item-details">
                        <div class="price-box price-final_price" >
    

						<span class="price-container price-final_price tax weee">
						<?php 
						$priceFormat = number_format($product->getPrice(), 2, '.', '');  // Last two parameters are optional

						
						?>
								<span id="product-price-<?php echo $priceFormat?>" class="price-wrapper "><span class="price">$<?php echo $priceFormat?></span></span>
								</span>

						</div> 
						<strong class="product name product-item-name">
                            <a class="product-item-link" href="$product->getUrl()">
                                     <?php echo $product->getName() ?><br />
							</a>
                        </strong>
                                                
                        </div>
				
			</div>
			</li>
        <?php $i++; endforeach; ?>
		<script type="text/javascript">
	require(['jquery'],function($){
		$(document).ready(function(){
			$('li.item.product.product-item').hover(function(){
				$(this).find('.product-item-inner').css({'position':'relative','top':'-4em'});
				$(this).find('.product-item-actions').show();
			});
			$('li.item.product.product-item').mouseleave(function(){
				$('ol li').find('.product-item-actions').each(function(){
					$(this).hide();
				});
				$(this).find('.product-item-inner').css({'position':'relative','top':'0em'});
				$(this).find('.product-item-actions').hide();
			});
		});
		
	});
	</script>
    </ol>
			
		  <ol class="products list items product-items list-mode" style="display:none;">
        <?php foreach ($_productCollection as $product) : ?>

		<?php
		$imageUrl = $helperImport->init($product, 'product_page_image_small')
                ->setImageFile($product->getSmallImage()) // image,small_image,thumbnail
                ->resize(380)
                ->getUrl();
		
		?>
            <li class="item product product-item" style="height:550px;width:100%">
			<div class="product-item-info" >
				  <div class="product-img-block" style="width: 30%;float: left;">
                         <a href="<?php echo $product->getProductUrl();?>" class="product photo product-item-photo" tabindex="-1">
						 <span class="product-image-container" style="width:300px;height:400px;">
							<span class="product-image-wrapper" style="padding-bottom: 125%;">
								<img class="product-image-photo" src="<?php echo $imageUrl;?>" max-width="300" max-height="375" alt=""></span>
						</span>
						<div class="pro-overlay"></div>
						</a>
					
                    </div>
							<div class="product-item-inner" style="position: relative;    top: 12em;float: left;width: 50%;">
						
								<div class="product actions product-item-actions" style="text-align:left;">
									
										
										<?php if ($product->getIsSalable()): ?>
												<!--<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>-->
												<div class="actions-primary">
										<button type="submit" id="product-item-<?php echo $product->getId() ?>" title="Add to Cart" class="product-item action tocart primary"><span>Add to Cart</span></button> 
										</div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<div class="actions-secondary">
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a style="text-align:left" href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>' class="action towishlist" data-action="add-to-wishlist">
												<span>Add to wishlist</span>
											</a>

										<?php endif; ?>
										<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
										<a style="text-align:left" href="#"
									   class="action tocompare"
									   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product); ?>'
									   role="button">
										<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
										</a>
										<div class="product description product-item-description">
								<?php echo $product->getDescription();?>
								<a href="<?php echo $product->getUrl();?>" title="<?php echo $product->getName();?>" class="action more">Learn More</a>
                            </div>
										</div>
									
							</div>
							
						</div>	
						<div class="product details product-item-details" style="width: 50%;float: left;text-align:left;">
                        <div class="price-box price-final_price" >
    

						<span class="price-container price-final_price tax weee">
						<?php 
						$priceFormat = number_format($product->getPrice(), 2, '.', '');  // Last two parameters are optional

						
						?>
								<span id="product-price-<?php echo $priceFormat?>" class="price-wrapper "><span class="price">$<?php echo $priceFormat?></span></span>
								</span>

						</div> 
						<strong class="product name product-item-name">
                            <a class="product-item-link" href="$product->getUrl()">
                                     <?php echo $product->getName() ?><br />
							</a>
                        </strong>
                                                
                        </div>
				
			</div>
			</li>
        <?php endforeach; ?>
		
    </ol>

	
<input type="hidden" id="add-cart-url" value="<?php echo $block->getUrl('amfinder/index/addToCart'); ?>">
		<?php endif;?>
	<style>
	.column.main .product-item{width: 33.3%;float: left;}
	li.item.product.product-item::hover{}
	.product-item-actions .actions-primary + .actions-secondary,.catalog-category-view button.action.primary.tocart{width: 100%;    float: left;}
	.product-item-actions{display:none;text-align:-webkit-center;  }
	.product-item-actions .actions-primary{top: -2em;position: relative;}
	.product-item{    border-right: 1px solid #e6e6e6;border-bottom: 1px solid #e6e6e6; border-top: 1px solid #e6e6e6;}
li:nth-child(3n){border-right:none}	
.column.main .product-item{}
.order-products-toolbar .pager .limiter{display:block !important;}
.toolbar-amount .toolbar-number{display:none !important;}
.toolbar-amount .toolbar-num{display:block !important;}
.pages .items{float:left;}
.order-products-toolbar .pager{    position: relative;top: 20px;}
.order-products-toolbar{float: right;    width: 100%;}
	</style>
	<script type="text/javascript">
	require(['jquery'],function($){
		$(document).ready(function(){
			var iValue = "<?php echo $i?>";
			if(iValue%2==0){
				$('.order-products-toolbar .pager .limiter').css({'width':'100%','text-align':'right','float':'right'});
			}
			var amfind = setInterval(function(){
			if($('.amfinder-vertical, .amfinder-horizontal').length){
				$('.amfinder-vertical, .amfinder-horizontal').hide();
				clearInterval(amfind);							
			}	
			},1000);
			
		});
		
	});
	</script>
	<script>
    require(['jquery','Magento_Customer/js/customer-data'],function($,customerData){
        $('.tocart').click(function(){
			
			$('.addtoc').each(function(){
				$(this).removeClass('addtoc');
			});
			$(this).addClass('addtoc');
			$(this).addClass('disabled');
			$('.addtoc').find('span').text('Adding');
            var productId = $(this).attr('id');
            productId = productId.replace('product-item-','');
            var data = {product: productId};
            var addToCartUrl = $('#add-cart-url').val();
            $.ajax({
                url : addToCartUrl,
                dataType : 'json',
                type : 'POST',
                data: data,
                success : function(data)
                {
					$('ul.messages').remove();
					
					setTimeout(function(){
					$('.addtoc').find('span').text('Add To Cart');
					$('.addtoc').removeClass('disabled');
					
					if(data.status=='error' && data.message=="The requested qty is not available"){
						alert('The requested qty is not available');
					}else if(data.status=='success'){
						jQuery(".page-title").after("<ul class='messages'><li class='success-msg'><ul><li><span>You added "+data.productname+" to your <a href='"+data.producturl+"'>shopping cart.</a></span></li></ul></li></ul>");
						$('.addtoc').find('span').text('Added');
						console.log('Success');
						var sections = ['cart'];
						customerData.invalidate(sections);
						customerData.reload(sections, true);
					}
					},2000);

                },
                error : function()
                {
                    console.log('error');
					$('.addtoc').find('span').text('Add To Cart');
                }
				
            });
        })
    })
</script>
<style>
ul.messages{
	margin: 0 0 10px;
    padding: 12px 20px 12px 25px;
    display: block;
    font-size: 1.3rem;
    background: #e5efe5;
    color: #006400;
    padding-left: 45px;
    position: relative;
}
.success-msg li span::before{
	font-size: 24px;
    line-height: 24px;
    color: #006400;
    content: '\e60e';
    font-family: 'luma-icons';
    margin: -12px 0 0;
    vertical-align: middle;
    display: inline-block;
    font-weight: normal;
    overflow: hidden;
    speak: none;
    left: 0;
    top: 22px;
    width: 45px;
    position: absolute;
    text-align: center;
}
.success-msg ul li{list-style-type: none;}
</style>
<?php 
		if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
		
<?php endif; }?>