<?php

// @codingStandardsIgnoreFile

/** @var \MW\Onestepcheckout\Block\Adminhtml\Sales\Order\View\Tab\Information $block */
$delivery = $block->getDelivery();
?>
<?php if($this->getLastItem()) {?>
	<?php echo "</table>"; ?>
<?php if (count($delivery) > 0) :?>
<div class="entry-edit">
	<fieldset>	
	<div class="delivery">
		<div class="entry-edit-head">
			<h4 class="icon-head head-account">
				<?php echo $block->escapeHtml(__('Time of Delivery')) ?>
			</h4>								
		</div>
	</div>
	<div class="grid">
		<div class="hor-scroll">
			<table cellspacing="0" class="data">
				<tbody>					
					<tr class="odd">
						
						<td class="a-left" style="height:35px;line-height:35px;font-weight:bold;padding-left:10px;">
							<p><?php echo $block->escapeHtml($delivery['mw_deliverydate_date'] . ' ' . $delivery['mw_deliverydate_time']);  ?></p>
							<p><?php echo $block->escapeHtml($delivery['mw_deliverydate_securitycode']);?></p>
						</td>						
					</tr>														
													
				</tbody>
			</table>
		</div>
	</div>
	</fieldset>
</div>
<?php endif;?>
<?php } ?>